vote:
  repository: "quackusarle/vote"
  tag: "14"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "250m"

result:
  repository: "quackusarle/result"
  tag: "3"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "250m"

worker:
  repository: "quackusarle/worker"
  tag: "4"
  replicaCount: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

redis:
  image:
    repository: "redis"
    tag: "alpine"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 6379

db:
  image:
    repository: "postgres"
    tag: "15-alpine"
  replicaCount: 1
  env:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
  service:
    type: ClusterIP
    port: 5432