vote:
  repository: "quackusarle/vote"
  tag: "initial-tag"
  replicaCount: 1
  service:
    type: NodePort
    port: 8080
    targetPort: 80
    nodePort: 31000

result:
  repository: "quackusarle/result"
  tag: "2"
  replicaCount: 1
  service:
    type: NodePort
    port: 8081
    targetPort: 80
    nodePort: 31001

worker:
  repository: "quackusarle/worker"
  tag: "2"
  replicaCount: 1

redis:
  image:
    repository: "redis"
    tag: "alpine"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 6379

db:
  image:
    repository: "postgres"
    tag: "15-alpine"
  replicaCount: 1
  env:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
  service:
    type: ClusterIP
    port: 5432